name: Build Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  build_maven_artifacts:
    name: Build Maven Artifacts
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Checkout geobroker-api
        uses: actions/checkout@v4
        with:
          repository: 'wrk-fmd/geobroker'
          path: 'geobroker'
          ref: "v1.1.0"

      - name: Checkout geobroker-client-api
        uses: actions/checkout@v4
        with:
          repository: 'robo-w/geobroker-client-lib'
          path: 'geobroker-client-lib'
          ref: "v1.0.0"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'kenwood-gps-converter'

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Build Geobroker API
        run: mvn clean install
        working-directory: 'geobroker/geobroker-api'

      - name: Build Geobroker Client Lib
        run: mvn clean install
        working-directory: 'geobroker-client-lib'

      - name: Build Full Project
        run: mvn clean install
        working-directory: 'kenwood-gps-converter'

      - name: Provide Kenwood GPS Converter
        uses: actions/upload-artifact@v4
        with:
          name: kenwood-gps-converter.jar
          path: kenwood-gps-converter/target/kenwood-gps-converter-*-jar-with-dependencies.jar
