name: Build Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  build_maven_artifacts:
    name: Build Maven Artifacts
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Build Full Project
        run: mvn clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Provide Kenwood GPS Converter
        uses: actions/upload-artifact@v4
        with:
          name: kenwood-gps-converter.jar
          path: target/kenwood-gps-converter-*-jar-with-dependencies.jar
